apiVersion: v2
name: chainweb
description: Chainweb Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 2.5
dependencies:
- name: cert-manager
  version: 1.2.0
  repository: https://charts.jetstack.io
  condition: installCertManager
- name: ingress-nginx
  version: 3.23.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress.enabled
